version: '1.0'

networks:
  node-api-networks:
    name: node-api-networks

services:
  api:
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    ports:
      - '8001:8000'
    depends_on:
      - mysql_server
    networks:
      - node-api-networks

  web:
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - api
    networks:
      - node-api-networks

  mysql_server:
    image: mysql:8.0
    ports:
      - '4404:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_kfc

    networks:
      - node-api-networks
